config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'
  post '/login', to: 'login#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    namespace :api, defaults: { format: :json } do
    namespace :v1 do
    put "/login", to: "login#login"
    resources :users, only: [:index, :show, :create, :update]
    resources :courses, only: [:index, :show, :create, :destroy, :update]
    resources :answers, only: [:show, :create]
    resources :questions, only: [:index ]
    resources :chapters
    post "/useranswer", to: "questions#useranswer"
    get "/useranswer", to: "questions#getresult"
    post "/joincourse", to: "courses#joincourse"
    get "/getusercourses", to: "courses#getusercourses"
    get "/getcolleagues", to: "companies#getcolleagues"
    get "/getcompany", to: "companies#getcompany"
    get "/userstats", to: "courses#userstats"
    # get "/questions", to: "questions#actionname"
    # resrouces :
    #   # /answers/:id/questions
    #   resources :questions
    #   # /answers/:id/choices
    #   resources :choices
    end
  end
  resources :courses do
    resources :questions
  end

  resources :questions do
    resources :choices
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :course
  has_many :choices, dependent: :destroy
  has_many :user_answers
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token, only: [:useranswer]
  def index
    course_id = params[:course_id]
    # Find all the questions base on the course id
    @questions = Question.where(course_id: course_id)
    # render json: @questions
  end

  def useranswer
    answers = params[:answer]
    p answers


    answers.each do |answer|
      # ua = UserAnswer.new(answer)
      ans = UserAnswer.where(user_id: answer["user_id"], question_id: answer["question_id"])
      ans.destroy_all
      ua = UserAnswer.new(user_id: answer["user_id"], question_id: answer["question_id"], choice_id: answer["choice_id"])
      ua.save
      p ua.errors
    end
    render json: {status: :OK}
  end

  def getresult
    @results = UserAnswer.where(user_id: params["user_id"].to_i)
    @result_list = @results.select { |element| element.question.course.id == params["course_id"].to_i}
    @result_list = @result_list.last(4) ## Should be dynamic

    @sum = 0
    @result_list.each do |result|
      if result.choice.is_correct
        @sum += 25
      end
    end
    @points = @sum

    update_points(@results)
    @course = OngoingCourse.where(course_id: params["course_id"].to_i)
    @course[0].is_completed = true
    @course[0].save
  end

  private
  def answer_params
    params.require(:answer).permit(:user_id, :course_id, :question_id)
  end

  def update_points(results)
    sum = 0
    results.each do |result|
      if result.choice.is_correct
        sum += 25
      end
    end
    user = User.find(results.last.user_id)
    user.user_points = sum
    user.save
  end

end
# link_to "Label", :controller => :my_controller, :action => :index

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :update, :edit, :destroy]
  def index
    course = params[:course_id]
    @questions = Question.where(course_id: course)
  end

  def show
  end

  def new
    @course = Course.find(params[:course_id])
    p @course
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @course = Course.find(params[:course_id])
    @question.course = @course
    @question.save

    redirect_to @question

    ## When you save it
    ## it should create a question first
    ## Question id is used for choice createh
  end

  def edit
    @question.edit(question_params)
      render json: {question: @question, status: :edited}
  end

  def update
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: "The question has been deleted."
  end

  private

  def question_params
    params.require(:question).permit(:question, :course_id)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/views/questions/edit.html.erb
<h1> Edit </h1>
<%= simple_form_for [ @question, @choice ] do |f| %>
    <%= f.input :question %>
    <%= f.input :choices %>

    <%= f.submit %>
<% end %>

<%= link_to 'Show', course_path %>
<%= link_to 'Back', courses_path %>

app/views/questions/index.html.erb
<!-- show question, choices
http://localhost:3000/courses/:id/questions
@questions = Question.where(course_id: a)

 -->
<h1>Quiz</h1>

<table>
      <tr>Question:</tr>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
          <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<%= simple_form_for [@course, @question] do |f| %>
  <%= f.input :question %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', courses_path %>
<%= link_to 'Create', questions_path %>

app/views/questions/show.html.erb
<!-- http://localhost:3000/courses/:id/questions/:id

Shows THE question

shows the choices with question_id (by default shows nothing, because you dont have choices)
@choices = Choice.where(question)
add new choice

http://localhost:3000/questions/:id/choices/new


Question: How do you become a green bar? -->




<%= @question.question %>
  <tr>Choices:</tr>
    <br>
      <% @question.choices.each do |choice| %>
        <p><%= choice.answer %></p>
    <% end %>

<%= link_to 'New Choice', new_question_choice_path(@question) %>